workflows:
  ios-workflow:
    name: Build NRO iOS (Unsigned)
    environment:
      xcode: latest
    scripts:
      - name: Build Xcode Project
        script: |
          xcodebuild build -project Unity-iPhone.xcodeproj -scheme Unity-iPhone -configuration Release -arch arm64 -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO CONFIGURATION_BUILD_DIR=build/Build/Products/Release-iphoneos
      - name: Package to IPA for Sideloadly
        script: |
          mkdir -p Payload
          mv build/Build/Products/Release-iphoneos/*.app Payload/
          zip -r NroIOS.ipa Payload
    artifacts:
      - NroIOS.ipa
